@base = http://localhost:3000/api/v1

### 201 - ticket created
POST {{base}}/tickets
Content-Type: application/json

{ "serviceId": "a1ab113e-37ab-4f23-842b-8e18dbc516f1" }

### 404 - service does not exist
POST {{base}}/tickets
Content-Type: application/json

{ "serviceId": "00000000-0000-0000-0000-000000000000" }

### 422 - missing serviceId
POST {{base}}/tickets
Content-Type: application/json

{}

### 422 - invalid serviceId
POST {{base}}/tickets
Content-Type: application/json

{ "serviceId": "abc" }

### 400 - JSON
POST {{base}}/tickets
Content-Type: application/json

{ "serviceId":

### 415 - wrong content type
POST {{base}}/tickets
Content-Type: text/plain

ciao

### 200 - get ticket queues
GET {{base}}/tickets/queues
